### ISSUE TITLE
Pruning and restarting the same network should not prune TLS certs in caddy

### ISSUE THREAD

**Issue by vedhavyas** [subspace/infra#104]
At the moment, when we prune and start the same testnet in the node, we are also pruning caddy volume which in turns remove all the TLS certs it has configured. Ideally, we do not want to prune the certs and let caddy handle it.

Potential solution:

Use host filesystem directly instead of docker volume so that pruning entire docker state will not prune those certs. Even if the testnet changes, caddy is already provided with appropriate tesnet domain it should not be an issue.

**Comment by DaMandal0rian** [comment]
Closing this issue as this was resolved in https://github.com/subspace/infra/pull/189/files
