### ISSUE TITLE
Ability to create/update/delete node keys when node state changes.

### ISSUE THREAD

**Issue by vedhavyas** [subspace/infra#85]
Right now the node keys the script creates at the start of the network. If there are any changes in the Node IP order where an IP might have been changed or removed, the node keys are not updated accordingly. Ideally, we want to ensure once an IP is assigned a key, it should not change. If an new IP gets added at a later time, it should get a new node key and the key files should be updated accordingly. Right now, its just a script but maybe it could be Go or Python or Rust app that does the following
- Take list of IPs and a node key file
- Verify the IP in list has a key assigned in the file
- Remove any deleted node keys from the file

**Comment by DaMandal0rian** [comment]
Will also integrate infra#85 to use this solution:
For more info: https://developer.hashicorp.com/vault/tutorials/secrets-management/versioned-kv
