### ISSUE TITLE
Ability to sync node keys, keystore etc... to bitwarden or other storage instead of manually doing it

### ISSUE THREAD

**Issue by vedhavyas** [subspace/infra#86]
At the moment, node key files we generate for each testnet are manully synced to Bitwarden. There is actually a bitwarden-cli that can help with syncing node keys of locally unavailable and uploding the updated keys locally to bitwarden. 

Once this is achived, anyone in infra team with required access can deploy while the state is fully shared across the team

**Comment by DaMandal0rian** [comment]
I was thinking we can use hashicorp vault with key engine v2 which supports versioning.
For more info: https://developer.hashicorp.com/vault/tutorials/secrets-management/versioned-kv
